version: '3.4'

networks:
  mercavus:
    driver: bridge
services:
  node:
    container_name: mercavus-node
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
      target: base
    ports:
      - "4000:3030"
    volumes:
      - ./:/home/node/app
    environment:
      TZ: CET
      http__port: 3030
      mongoose__url: mongodb://root:root_password@mongo:27017/mercavus?authSource=admin
    depends_on:
      - mongo
    logging: #read them from /var/lib/docker/containers/*/*-json.log
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "100"
    restart: always
    networks:
      - mercavus
    command: ["./docker/wait-for.sh", "mongo:27017", "--", "npm", "run" ,"watch"]

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: mercavus
    volumes:
      - ./data_dir:/data/db
    networks:
      - mercavus
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_password
    networks:
      - mercavus

